"""
Full end-to-end mock run against LocalStack (fake AWS in Docker).

Unlike run_local.py (which uses a canned mock boto3 session), this exercises the
REAL AWS layer: CloudFormation-deployed fixtures in LocalStack, the real provisioner
manifest, real boto3 catalog calls, and a local Ollama model as the agent under test.

Prerequisites (see local_test/README.md):
  - LocalStack running on :4566 with the wafr-* fixture stacks deployed
  - benchmark/env_manifest.json generated by `python -m runner.provisioner`
  - AWS_ENDPOINT_URL=http://localhost:4566 and dummy AWS creds in the environment
  - Ollama serving a tool-capable model (OLLAMA_MODEL, default qwen3.5:9b)

Usage:
    python -m local_test.run_localstack <csv_id>
"""

import os
import sys
import time
import threading

import boto3

from local_test.agent_bridge import make_server
from runner.provisioner import load_manifest
from runner.loader import load_scenario, load_gold
from runner.resolver import ManifestResolver
from runner.agents.toolloop import ToolLoopAdapter
from runner.capture import capture, print_capture
from runner.evaluator import evaluate, print_evaluation

BRIDGE_PORT = int(os.getenv("BRIDGE_PORT", "8099"))
DEFAULT_SCENARIO = "COPS-point-in-time-recovery-disable-L1-952c1416"


def main():
    csv_id = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SCENARIO

    server = make_server(port=BRIDGE_PORT)
    threading.Thread(target=server.serve_forever, daemon=True).start()
    time.sleep(0.3)
    endpoint = f"http://127.0.0.1:{BRIDGE_PORT}"
    print(f"\n  bridge   : {endpoint} (→ Ollama {os.getenv('OLLAMA_MODEL','qwen3.5:9b')})")
    print(f"  aws      : {os.getenv('AWS_ENDPOINT_URL')} (LocalStack)")

    env = load_manifest()
    resolver = ManifestResolver(env)
    gold = resolver.resolve_gold(load_gold(csv_id))
    scenario = load_scenario(csv_id)
    print(f"  scenario : {csv_id}")
    print(f"  correct  : {gold.get('correct_resources')}")
    print(f"  expect   : {[t['tool'] for t in gold.get('expected_tools', [])]}")
    if gold.get("_unresolved"):
        print(f"  [note] unresolved handles (fixture not deployed): {gold['_unresolved']}")

    # REAL boto3 session — AWS_ENDPOINT_URL routes it to LocalStack
    session = boto3.Session(region_name=env.get("region", "us-east-1"))
    adapter = ToolLoopAdapter(region=env.get("region", "us-east-1"), endpoint=endpoint, session=session)

    print("\n  [running agent through the tool loop against LocalStack...]\n")
    agent_input = adapter.build_input(scenario, gold, env)
    result = adapter.run(agent_input).to_capture_dict()
    print(f"  tools called: {[tc['tool'] for tc in result['tool_calls']]}")

    captured = capture(result, csv_id, gold)
    eval_result = evaluate(captured, gold, observable_tools=True, native_tools=True)
    print_capture(captured)
    print_evaluation(eval_result)

    server.shutdown()
    print("\n  LocalStack end-to-end run complete.")
    return eval_result


if __name__ == "__main__":
    main()
